### ISSUE TITLE
Support Godot4 and .NET6

### ISSUE THREAD

**Issue by GeorgeS2019** [j20001970/GDMP-demo#1]

**Comment by j20001970** [comment]
The plugin and demo for godot4 is being worked on. Although most functionality is still not working, the progress can be seen on `4.0` branch.

.NET6 support will likely be planned after porting to godot4 (GDExtension) is done, as it isn't quite clear to me at the moment that how to incorporate with the two system.

BTW, although I haven't tried it myself, maybe [MediaPipe.NET](https://github.com/vignetteapp/MediaPipe.NET) will work for you if .NET is primarily used in the project.

**Comment by GeorgeS2019** [comment]
I will write C# to interop GD script if necessary for Windows Desktop (Now working. Thank you)
