### ISSUE TITLE
GDMP-Demo windows loading GDMP.dll fails

### ISSUE THREAD

**Issue by GeorgeS2019** [j20001970/GDMP-demo#10]
using the latest commit. Fail to load GDMP.dll

```
  core/extension/gdextension.cpp:593 - GDExtension configuration file must contain a "configuration/compatibility_minimum" 

key: res://addons/GDMP/GDMP.gdextension
  Failed loading resource: res://addons/GDMP/GDMP.gdextension. 

Make sure resources have been imported by opening the project in the editor at least once.
```

**Comment by j20001970** [comment]
I'm investigating the issue.

**Comment by j20001970** [comment]
It seems that since Godot v4.1, `.gdextension` file need to specify minimum supported version of the libraries.

Please make sure to update `GDMP.gdextension` of your project using `addons/GDMP/GDMP.gdextension` on the GDMP latest commit.

**Comment by GeorgeS2019** [comment]
https://github.com/j20001970/GDMP/blob/master/addons/GDMP/GDMP.gdextension

This clashes the godot

Do consider distributing Windows binary so we have a better idea of where the problem is for Windows.

**Comment by GeorgeS2019** [comment]
The GDMP.dll is attached. I tested. The problem is resolved. Thank you
