### ISSUE TITLE
Demo Doesent seem to work

### ISSUE THREAD

**Issue by gro-david** [j20001970/GDMP-demo#17]
After downloading the demo and also initializing the submodules, it cant find the stuff related to mediapipe ```MediaPipeTask cant be found```. The binary also isnt there.

**Comment by gro-david** [comment]
I have these files, so the clone was indeed succesful. I am on Linux, and i do have opencv installed. I do not have libopencv_core.so.408 but i can find libopencv_core.so.409 in /usr/local/lib (which is in my path. 
``` Can't open dynamic library: /home/macisajt/Downloads/GDMP-demo/project/addons/GDMP/libs/x86_64/libGDMP.so. Error: libopencv_core.so.408: cannot open shared object file: No such file or directory.
  core/extension/gdextension.cpp:719 - GDExtension dynamic library not found: /home/macisajt/Downloads/GDMP-demo/project/addons/GDMP/libs/x86_64/libGDMP.so
  Failed loading resource: res://addons/GDMP/GDMP.gdextension. Make sure resources have been imported by opening the project in the editor at least once.```
These are the errors i am getting.

**Comment by j20001970** [comment]
> I have these files, so the clone was indeed succesful. I am on Linux, and i do have opencv installed. I do not have libopencv_core.so.408 but i can find libopencv_core.so.409 in /usr/local/lib (which is in my path.
> 
> `Can't open dynamic library: /home/macisajt/Downloads/GDMP-demo/project/addons/GDMP/libs/x86_64/libGDMP.so. Error: libopencv_core.so.408: cannot open shared object file: No such file or directory. core/extension/gdextension.cpp:719 - GDExtension dynamic library not found: /home/macisajt/Downloads/GDMP-demo/project/addons/GDMP/libs/x86_64/libGDMP.so Failed loading resource: res://addons/GDMP/GDMP.gdextension. Make sure resources have been imported by opening the project in the editor at least once.`
> 
> These are the errors i am getting.

In that case, you will need to patch the library to link OpenCV version on your host, or recompile the library yourself.

Using `readelf -d libGDMP.so`, you can see the libraries required by `libGDMP.so`

```
$ readelf -d libGDMP.so

Dynamic section at offset 0x16495f8 contains 42 entries:
  Tag        Type                         Name/Value
 0x0000000000000003 (PLTGOT)             0x1657460
 0x0000000000000002 (PLTRELSZ)           475680 (bytes)
 0x0000000000000017 (JMPREL)             0x50c1e8
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000007 (RELA)               0x44b8e8
 0x0000000000000008 (RELASZ)             788736 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffff9 (RELACOUNT)          3795
 0x0000000000000006 (SYMTAB)             0x2b8
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000005 (STRTAB)             0xde7f8
 0x000000000000000a (STRSZ)              3202701 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x3ec688
 0x0000000000000001 (NEEDED)             Shared library: [libopencv_core.so.408]
 0x0000000000000001 (NEEDED)             Shared library: [libopencv_calib3d.so.408]
 0x0000000000000001 (NEEDED)             Shared library: [libopencv_features2d.so.408]
 0x0000000000000001 (NEEDED)             Shared library: [libopencv_highgui.so.408]
 0x0000000000000001 (NEEDED)             Shared library: [libopencv_imgcodecs.so.408]
 0x0000000000000001 (NEEDED)             Shared library: [libopencv_imgproc.so.408]
 0x0000000000000001 (NEEDED)             Shared library: [libopencv_video.so.408]
 0x0000000000000001 (NEEDED)             Shared library: [libopencv_videoio.so.408]
 0x0000000000000001 (NEEDED)             Shared library: [libGLESv2.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libEGL.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
```

Then use `patchelf` to replace `libopencv_*.so.408` to `libopencv_*.so.409`, for example:

`$ patchelf --replace-needed libopencv_core.so.408 libopencv_core.so.409 libGDMP.so`

After replacing `libopencv_*.so` to the version installed on your host, it should start working.

**Comment by gro-david** [comment]
I have replaced these libraries, so thats not an issue anymore. Thanks so much!
But unfortunately another error occurred, this time Godot wont even start, crashes as soon as I want to open the editor with the project. This is the error I am getting:

```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.2.1.stable.arch_linux
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/libc.so.6(+0x3c770) [0x700493c5a770] (??:0)
-- END OF BACKTRACE --
================================================================
fish: Job 1, 'godot project.godot' terminated by signal SIGABRT (Abort)
```

I have looked if the mentioned file `/usr/lib/libc.so.6` which does exist. After looking it up online I am suspecting that its a 'segmentation fault' but I have no experience, what so ever, with c++ programming so I cant really do anything with this knowledge unfortunately. 
I hope you can help.

**Comment by gro-david** [comment]
Thank you very much, that worked perfectly.
